- hosts: terraform-ansible
  tasks:
    - name: instalando python3 com virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes

    - name: instalando dependencias com pip (Django e Django REST)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework

    - name: iniciando projeto com Ansible
      shell: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup  /home/ubuntu/tcc/"

    - name: alterando host do settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
